image: nixos/unstable
packages:
  - nixos.git
  - nixos.openssl
secrets:
  - 830f5de1-eca9-4be4-918d-5c16d93ece94
  - 5a3d4226-6ffc-4a46-a3e3-2b2d129c8f49
sources:
  - https://git.sr.ht/~haoxiangliew/nixos
tasks:
  - validate-gh-fingerprint-and-configure-ssh: |
      tmp_dir=$(mktemp -d -p $HOME)
      ssh-keyscan -t rsa github.com > $tmp_dir/github_host
      ssh-keygen -lf $tmp_dir/github_host > $tmp_dir/github_fingerprint
      grep -R "nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8" $tmp_dir/github_fingerprint
      cat $tmp_dir/github_host >> ~/.ssh/known_hosts
      rm -rf $tmp_dir
      echo -e "Host github.com\n    IdentityFile ~/.ssh/id_rsa\n    IdentitiesOnly yes\n    BatchMode yes\n" >> ~/.ssh/config
      eval $(ssh-agent -s)
      echo 'cat ~/.ssh/ssh_passphrase' > ~/.ssh/print_ssh_passphrase
      chmod +x ~/.ssh/print_ssh_passphrase
      cat ~/.ssh/id_rsa | tr -d '\r' | DISPLAY=":0.0" SSH_ASKPASS=~/.ssh/print_ssh_passphrase setsid ssh-add - > /dev/null
  - mirror-to-github: |
      cd ~/nixos
      git remote add github git@github.com:haoxiangliew/nixos.git
      git push --mirror github
