image: nixos/unstable
packages:
  - git
secrets:
- 830f5de1-eca9-4be4-918d-5c16d93ece94
- e929f7a1-be7c-4e35-8d27-f41d897f0cba
tasks:
  - validate-gh-fingerprint-and-configure-ssh: |
      temp_dir=$(mktemp -d -p $HOME)
      ssh-keyscan -t rsa github.com > $temp_dir/github_host
      ssh-keygen -lf $temp_dir/github_host > $temp_dir/github_fingerprint
      grep -R "nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8" $tmp_dir/github_fingerprint
      cat $tmp_dir/github_host >> ~/.ssh/known_hosts
      rm -rf $tmp_dir
      echo -e "Host github.com\n    IdentityFile ~/.ssh/id_rsa\n    IdentitiesOnly yes\n    BatchMode yes\n" >> ~/.ssh/config
  - mirror-to-github: |
      cd ~/.emacs.d
      git push --mirror git@github.com:haoxiangliew/.emacs.d.git
