# start numbering at 1
set -g base-index 1

# faster key repetition
set -s escape-time 0

# resize to max size of client
setw -g aggressive-resize on

# set better color
set -g default-terminal 'xterm-256color'
set -ga terminal-overrides ',xterm-256color:Tc'

# add a padded line so command mode in my editor is better
setw -g pane-border-status bottom
setw -g pane-border-format ''
