backend = "glx";

corner-radius = 10.0;
rounded-corners-exclude = [
  "window_type = 'dock'",
];

blur: {
  method = "kawase";
  strength = 10;
  background = false;
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
  "class_g = 'slop'",
];
