# browser is the shell (/bin/sh) command executed once the proxy starts.
# When browser exits, the proxy exits. An extra env var PROXY is available.
#
# Here, we use a separate Chrome instance in Incognito mode, so that
# it can run (and be waited for) alongside the default one, and that
# it maintains no state across runs. To configure this browser open a
# normal window in it, settings will be preserved.
browser = """
    google-chrome-unstable \
    --user-data-dir="$HOME/.google-chrome-captive" \
    --proxy-server="socks5://$PROXY" \
    --host-resolver-rules="MAP * ~NOTFOUND , EXCLUDE localhost" \
    --no-first-run --new-window --incognito \
    http://neverssl.com
"""

# Here, we use a separate Firefox instance in Private Browsing mode, so that
# it can run (and be waited for) alongside the default one, and that it
# maintains no state across runs. To configure this browser open a normal
# window in it, settings will be preserved.
#
# Ensure that up to one profile is named `captive-browser` before running this
# command, and that its profile directory in `$HOME/.mozilla/firefox` is the
# only one that ends with `.captive-browser`. You can check with
# `firefox --ProfileManager`. This should only be an issue if you've renamed a
# profile from `captive-browser` previously.
#
# browser = """\
#   firefox \
#   --CreateProfile \"captive-browser\" \
#   && printf \"user_pref%s;\\n\" \
#     \"(\\\"network.proxy.type\\\", 1)\" \
#     \"(\\\"network.proxy.socks_remote_dns\\\", true)\" \
#     \"(\\\"network.proxy.socks_version\\\", 5)\" \
#     \"(\\\"network.proxy.socks\\\", \\\"${PROXY%:*}\\\")\" \
#     \"(\\\"network.proxy.socks_port\\\", ${PROXY##*:})\" \
#     \"(\\\"network.proxy.no_proxies_on\\\", \\\"localhost, 127.0.0.1\\\")\" \
#     \"(\\\"dom.security.https_only_mode\\\", false)\" \
#   >> \"$(printf \"%s\\n\" \"$HOME\"/.mozilla/firefox/*.captive-browser/)\"prefs.js \
#   && firefox \
#   -P \"captive-browser\" \
#   --no-remote --private-window \
#   \"http://detectportal.firefox.com/success.txt\"\
# """

# dhcp-dns is the shell (/bin/sh) command executed to obtain the DHCP
# DNS server address. The first match of an IPv4 regex is used.
# IPv4 only, because let's be real, it's a captive portal.
#
# `wlp3s0` is your network interface (eth0, wlan0 ...)
#
dhcp-dns = "nmcli dev show | grep IP4.DNS"

# socks5-addr is the listen address for the SOCKS5 proxy server.
socks5-addr = "localhost:1666"